export const districts = [
    { Sid: "1", Did: "1", name: "Nicobars" },
    { Sid: "1", Did: "2", name: "North And Middle Andaman" },
    { Sid: "1", Did: "3", name: "South Andamans" },
    { Sid: "2", Did: "1", name: "Anantapur" },
    { Sid: "2", Did: "2", name: "Chittoor" },
    { Sid: "2", Did: "3", name: "East Godavari" },
    { Sid: "2", Did: "4", name: "Guntur" },
    { Sid: "2", Did: "5", name: "Krishna" },
    { Sid: "2", Did: "6", name: "Kurnool" },
    { Sid: "2", Did: "7", name: "Prakasam" },
    { Sid: "2", Did: "8", name: "Spsr Nellore" },
    { Sid: "2", Did: "9", name: "Srikakulam" },
    { Sid: "2", Did: "10", name: "Visakhapatanam" },
    { Sid: "2", Did: "11", name: "Vizianagaram" },
    { Sid: "2", Did: "12", name: "West Godavari" },
    { Sid: "2", Did: "13", name: "Y.s.r." },
    { Sid: "3", Did: "1", name: "Anjaw" },
    { Sid: "3", Did: "2", name: "Changlang" },
    { Sid: "3", Did: "3", name: "Dibang Valley" },
    { Sid: "3", Did: "4", name: "East Kameng" },
    { Sid: "3", Did: "5", name: "East Siang" },
    { Sid: "3", Did: "6", name: "Kamle" },
    { Sid: "3", Did: "7", name: "Kra Daadi" },
    { Sid: "3", Did: "8", name: "Kurung Kumey" },
    { Sid: "3", Did: "9", name: "Leparada" },
    { Sid: "3", Did: "10", name: "Lohit" },
    { Sid: "3", Did: "11", name: "Longding" },
    { Sid: "3", Did: "12", name: "Lower Dibang Valley" },
    { Sid: "3", Did: "13", name: "Lower Siang" },
    { Sid: "3", Did: "14", name: "Lower Subansiri" },
    { Sid: "3", Did: "15", name: "Namsai" },
    { Sid: "3", Did: "16", name: "Pakke Kessang" },
    { Sid: "3", Did: "17", name: "Papum Pare" },
    { Sid: "3", Did: "18", name: "Shi Yomi" },
    { Sid: "3", Did: "19", name: "Siang" },
    { Sid: "3", Did: "20", name: "Tawang" },
    { Sid: "3", Did: "21", name: "Tirap" },
    { Sid: "3", Did: "22", name: "Upper Siang" },
    { Sid: "3", Did: "23", name: "Upper Subansiri" },
    { Sid: "3", Did: "24", name: "West Kameng" },
    { Sid: "3", Did: "25", name: "West Siang" },
    { Sid: "4", Did: "1", name: "Baksa" },
    { Sid: "4", Did: "2", name: "Barpeta" },
    { Sid: "4", Did: "3", name: "Biswanath" },
    { Sid: "4", Did: "4", name: "Bongaigaon" },
    { Sid: "4", Did: "5", name: "Cachar" },
    { Sid: "4", Did: "6", name: "Charaideo" },
    { Sid: "4", Did: "7", name: "Chirang" },
    { Sid: "4", Did: "8", name: "Darrang" },
    { Sid: "4", Did: "9", name: "Dhemaji" },
    { Sid: "4", Did: "10", name: "Dhubri" },
    { Sid: "4", Did: "11", name: "Dibrugarh" },
    { Sid: "4", Did: "12", name: "Dima Hasao" },
    { Sid: "4", Did: "13", name: "Goalpara" },
    { Sid: "4", Did: "14", name: "Golaghat" },
    { Sid: "4", Did: "15", name: "Hailakandi" },
    { Sid: "4", Did: "16", name: "Hojai" },
    { Sid: "4", Did: "17", name: "Jorhat" },
    { Sid: "4", Did: "18", name: "Kamrup" },
    { Sid: "4", Did: "19", name: "Kamrup Metro" },
    { Sid: "4", Did: "20", name: "Karbi Anglong" },
    { Sid: "4", Did: "21", name: "Karimganj" },
    { Sid: "4", Did: "22", name: "Kokrajhar" },
    { Sid: "4", Did: "23", name: "Lakhimpur" },
    { Sid: "4", Did: "24", name: "Majuli" },
    { Sid: "4", Did: "25", name: "Marigaon" },
    { Sid: "4", Did: "26", name: "Nagaon" },
    { Sid: "4", Did: "27", name: "Nalbari" },
    { Sid: "4", Did: "28", name: "Sivasagar" },
    { Sid: "4", Did: "29", name: "Sonitpur" },
    { Sid: "4", Did: "30", name: "South Salmara Mancachar" },
    { Sid: "4", Did: "31", name: "Tinsukia" },
    { Sid: "4", Did: "32", name: "Udalguri" },
    { Sid: "4", Did: "33", name: "West Karbi Anglong" },
    { Sid: "5", Did: "1", name: "Araria" },
    { Sid: "5", Did: "2", name: "Arwal" },
    { Sid: "5", Did: "3", name: "Aurangabad" },
    { Sid: "5", Did: "4", name: "Banka" },
    { Sid: "5", Did: "5", name: "Begusarai" },
    { Sid: "5", Did: "6", name: "Bhagalpur" },
    { Sid: "5", Did: "7", name: "Bhojpur" },
    { Sid: "5", Did: "8", name: "Buxar" },
    { Sid: "5", Did: "9", name: "Darbhanga" },
    { Sid: "5", Did: "10", name: "Gaya" },
    { Sid: "5", Did: "11", name: "Gopalganj" },
    { Sid: "5", Did: "12", name: "Jamui" },
    { Sid: "5", Did: "13", name: "Jehanabad" },
    { Sid: "5", Did: "14", name: "Kaimur (bhabua)" },
    { Sid: "5", Did: "15", name: "Katihar" },
    { Sid: "5", Did: "16", name: "Khagaria" },
    { Sid: "5", Did: "17", name: "Kishanganj" },
    { Sid: "5", Did: "18", name: "Lakhisarai" },
    { Sid: "5", Did: "19", name: "Madhepura" },
    { Sid: "5", Did: "20", name: "Madhubani" },
    { Sid: "5", Did: "21", name: "Munger" },
    { Sid: "5", Did: "22", name: "Muzaffarpur" },
    { Sid: "5", Did: "23", name: "Nalanda" },
    { Sid: "5", Did: "24", name: "Nawada" },
    { Sid: "5", Did: "25", name: "Pashchim Champaran" },
    { Sid: "5", Did: "26", name: "Patna" },
    { Sid: "5", Did: "27", name: "Purbi Champaran" },
    { Sid: "5", Did: "28", name: "Purnia" },
    { Sid: "5", Did: "29", name: "Rohtas" },
    { Sid: "5", Did: "30", name: "Saharsa" },
    { Sid: "5", Did: "31", name: "Samastipur" },
    { Sid: "5", Did: "32", name: "Saran" },
    { Sid: "5", Did: "33", name: "Sheikhpura" },
    { Sid: "5", Did: "34", name: "Sheohar" },
    { Sid: "5", Did: "35", name: "Sitamarhi" },
    { Sid: "5", Did: "36", name: "Siwan" },
    { Sid: "5", Did: "37", name: "Supaul" },
    { Sid: "5", Did: "38", name: "Vaishali" },
    { Sid: "6", Did: "1", name: "Chandigarh" },
    { Sid: "7", Did: "1", name: "Balod" },
    { Sid: "7", Did: "2", name: "Baloda Bazar" },
    { Sid: "7", Did: "3", name: "Balrampur" },
    { Sid: "7", Did: "4", name: "Bastar" },
    { Sid: "7", Did: "5", name: "Bemetara" },
    { Sid: "7", Did: "6", name: "Bijapur" },
    { Sid: "7", Did: "7", name: "Bilaspur" },
    { Sid: "7", Did: "8", name: "Dantewada" },
    { Sid: "7", Did: "9", name: "Dhamtari" },
    { Sid: "7", Did: "10", name: "Durg" },
    { Sid: "7", Did: "11", name: "Gariyaband" },
    { Sid: "7", Did: "12", name: "Gaurella Pendra Marwahi" },
    { Sid: "7", Did: "13", name: "Janjgir-champa" },
    { Sid: "7", Did: "14", name: "Jashpur" },
    { Sid: "7", Did: "15", name: "Kabirdham" },
    { Sid: "7", Did: "16", name: "Kanker" },
    { Sid: "7", Did: "17", name: "Kondagaon" },
    { Sid: "7", Did: "18", name: "Korba" },
    { Sid: "7", Did: "19", name: "Korea" },
    { Sid: "7", Did: "20", name: "Mahasamund" },
    { Sid: "7", Did: "21", name: "Mungeli" },
    { Sid: "7", Did: "22", name: "Narayanpur" },
    { Sid: "7", Did: "23", name: "Raigarh" },
    { Sid: "7", Did: "24", name: "Raipur" },
    { Sid: "7", Did: "25", name: "Rajnandgaon" },
    { Sid: "7", Did: "26", name: "Sukma" },
    { Sid: "7", Did: "27", name: "Surajpur" },
    { Sid: "7", Did: "28", name: "Surguja" },
    { Sid: "8", Did: "1", name: "Central" },
    { Sid: "8", Did: "2", name: "East" },
    { Sid: "8", Did: "3", name: "New Delhi" },
    { Sid: "8", Did: "4", name: "North" },
    { Sid: "8", Did: "5", name: "North East" },
    { Sid: "8", Did: "6", name: "North West" },
    { Sid: "8", Did: "7", name: "Shahdara" },
    { Sid: "8", Did: "8", name: "South" },
    { Sid: "8", Did: "9", name: "South East" },
    { Sid: "8", Did: "10", name: "South West" },
    { Sid: "8", Did: "11", name: "West" },
    { Sid: "9", Did: "1", name: "North Goa" },
    { Sid: "9", Did: "2", name: "South Goa" },
    { Sid: "10", Did: "1", name: "Ahmadabad" },
    { Sid: "10", Did: "2", name: "Amreli" },
    { Sid: "10", Did: "3", name: "Anand" },
    { Sid: "10", Did: "4", name: "Arvalli" },
    { Sid: "10", Did: "5", name: "Banas Kantha" },
    { Sid: "10", Did: "6", name: "Bharuch" },
    { Sid: "10", Did: "7", name: "Bhavnagar" },
    { Sid: "10", Did: "8", name: "Botad" },
    { Sid: "10", Did: "9", name: "Chhotaudepur" },
    { Sid: "10", Did: "10", name: "Dang" },
    { Sid: "10", Did: "11", name: "Devbhumi Dwarka" },
    { Sid: "10", Did: "12", name: "Dohad" },
    { Sid: "10", Did: "13", name: "Gandhinagar" },
    { Sid: "10", Did: "14", name: "Gir Somnath" },
    { Sid: "10", Did: "15", name: "Jamnagar" },
    { Sid: "10", Did: "16", name: "Junagadh" },
    { Sid: "10", Did: "17", name: "Kachchh" },
    { Sid: "10", Did: "18", name: "Kheda" },
    { Sid: "10", Did: "19", name: "Mahesana" },
    { Sid: "10", Did: "20", name: "Mahisagar" },
    { Sid: "10", Did: "21", name: "Morbi" },
    { Sid: "10", Did: "22", name: "Narmada" },
    { Sid: "10", Did: "23", name: "Navsari" },
    { Sid: "10", Did: "24", name: "Panch Mahals" },
    { Sid: "10", Did: "25", name: "Patan" },
    { Sid: "10", Did: "26", name: "Porbandar" },
    { Sid: "10", Did: "27", name: "Rajkot" },
    { Sid: "10", Did: "28", name: "Sabar Kantha" },
    { Sid: "10", Did: "29", name: "Surat" },
    { Sid: "10", Did: "30", name: "Surendranagar" },
    { Sid: "10", Did: "31", name: "Tapi" },
    { Sid: "10", Did: "32", name: "Vadodara" },
    { Sid: "10", Did: "33", name: "Valsad" },
    { Sid: "11", Did: "1", name: "Ambala" },
    { Sid: "11", Did: "2", name: "Bhiwani" },
    { Sid: "11", Did: "3", name: "Charki Dadri" },
    { Sid: "11", Did: "4", name: "Faridabad" },
    { Sid: "11", Did: "5", name: "Fatehabad" },
    { Sid: "11", Did: "6", name: "Gurugram" },
    { Sid: "11", Did: "7", name: "Hisar" },
    { Sid: "11", Did: "8", name: "Jhajjar" },
    { Sid: "11", Did: "9", name: "Jind" },
    { Sid: "11", Did: "10", name: "Kaithal" },
    { Sid: "11", Did: "11", name: "Karnal" },
    { Sid: "11", Did: "12", name: "Kurukshetra" },
    { Sid: "11", Did: "13", name: "Mahendragarh" },
    { Sid: "11", Did: "14", name: "Nuh" },
    { Sid: "11", Did: "15", name: "Palwal" },
    { Sid: "11", Did: "16", name: "Panchkula" },
    { Sid: "11", Did: "17", name: "Panipat" },
    { Sid: "11", Did: "18", name: "Rewari" },
    { Sid: "11", Did: "19", name: "Rohtak" },
    { Sid: "11", Did: "20", name: "Sirsa" },
    { Sid: "11", Did: "21", name: "Sonipat" },
    { Sid: "11", Did: "22", name: "Yamunanagar" },
    { Sid: "12", Did: "1", name: "Bilaspur" },
    { Sid: "12", Did: "2", name: "Chamba" },
    { Sid: "12", Did: "3", name: "Hamirpur" },
    { Sid: "12", Did: "4", name: "Kangra" },
    { Sid: "12", Did: "5", name: "Kinnaur" },
    { Sid: "12", Did: "6", name: "Kullu" },
    { Sid: "12", Did: "7", name: "Lahul And Spiti" },
    { Sid: "12", Did: "8", name: "Mandi" },
    { Sid: "12", Did: "9", name: "Shimla" },
    { Sid: "12", Did: "10", name: "Sirmaur" },
    { Sid: "12", Did: "11", name: "Solan" },
    { Sid: "12", Did: "12", name: "Una" },
    { Sid: "13", Did: "1", name: "Anantnag" },
    { Sid: "13", Did: "2", name: "Bandipora" },
    { Sid: "13", Did: "3", name: "Baramulla" },
    { Sid: "13", Did: "4", name: "Budgam" },
    { Sid: "13", Did: "5", name: "Doda" },
    { Sid: "13", Did: "6", name: "Ganderbal" },
    { Sid: "13", Did: "7", name: "Jammu" },
    { Sid: "13", Did: "8", name: "Kathua" },
    { Sid: "13", Did: "9", name: "Kishtwar" },
    { Sid: "13", Did: "10", name: "Kulgam" },
    { Sid: "13", Did: "11", name: "Kupwara" },
    { Sid: "13", Did: "12", name: "Poonch" },
    { Sid: "13", Did: "13", name: "Pulwama" },
    { Sid: "13", Did: "14", name: "Rajouri" },
    { Sid: "13", Did: "15", name: "Ramban" },
    { Sid: "13", Did: "16", name: "Reasi" },
    { Sid: "13", Did: "17", name: "Samba" },
    { Sid: "13", Did: "18", name: "Shopian" },
    { Sid: "13", Did: "19", name: "Srinagar" },
    { Sid: "13", Did: "20", name: "Udhampur" },
    { Sid: "14", Did: "1", name: "Bokaro" },
    { Sid: "14", Did: "2", name: "Chatra" },
    { Sid: "14", Did: "3", name: "Deoghar" },
    { Sid: "14", Did: "4", name: "Dhanbad" },
    { Sid: "14", Did: "5", name: "Dumka" },
    { Sid: "14", Did: "6", name: "East Singhbum" },
    { Sid: "14", Did: "7", name: "Garhwa" },
    { Sid: "14", Did: "8", name: "Giridih" },
    { Sid: "14", Did: "9", name: "Godda" },
    { Sid: "14", Did: "10", name: "Gumla" },
    { Sid: "14", Did: "11", name: "Hazaribagh" },
    { Sid: "14", Did: "12", name: "Jamtara" },
    { Sid: "14", Did: "13", name: "Khunti" },
    { Sid: "14", Did: "14", name: "Koderma" },
    { Sid: "14", Did: "15", name: "Latehar" },
    { Sid: "14", Did: "16", name: "Lohardaga" },
    { Sid: "14", Did: "17", name: "Pakur" },
    { Sid: "14", Did: "18", name: "Palamu" },
    { Sid: "14", Did: "19", name: "Ramgarh" },
    { Sid: "14", Did: "20", name: "Ranchi" },
    { Sid: "14", Did: "21", name: "Sahebganj" },
    { Sid: "14", Did: "22", name: "Saraikela Kharsawan" },
    { Sid: "14", Did: "23", name: "Simdega" },
    { Sid: "14", Did: "24", name: "West Singhbhum" },
    { Sid: "15", Did: "1", name: "Bagalkote" },
    { Sid: "15", Did: "2", name: "Ballari" },
    { Sid: "15", Did: "3", name: "Belagavi" },
    { Sid: "15", Did: "4", name: "Bengaluru Rural" },
    { Sid: "15", Did: "5", name: "Bengaluru Urban" },
    { Sid: "15", Did: "6", name: "Bidar" },
    { Sid: "15", Did: "7", name: "Chamarajanagara" },
    { Sid: "15", Did: "8", name: "Chikkaballapura" },
    { Sid: "15", Did: "9", name: "Chikkamagaluru" },
    { Sid: "15", Did: "10", name: "Chitradurga" },
    { Sid: "15", Did: "11", name: "Dakshina Kannada" },
    { Sid: "15", Did: "12", name: "Davangere" },
    { Sid: "15", Did: "13", name: "Dharwad" },
    { Sid: "15", Did: "14", name: "Gadag" },
    { Sid: "15", Did: "15", name: "Hassan" },
    { Sid: "15", Did: "16", name: "Haveri" },
    { Sid: "15", Did: "17", name: "Kalaburagi" },
    { Sid: "15", Did: "18", name: "Kodagu" },
    { Sid: "15", Did: "19", name: "Kolar" },
    { Sid: "15", Did: "20", name: "Koppal" },
    { Sid: "15", Did: "21", name: "Mandya" },
    { Sid: "15", Did: "22", name: "Mysuru" },
    { Sid: "15", Did: "23", name: "Raichur" },
    { Sid: "15", Did: "24", name: "Ramanagara" },
    { Sid: "15", Did: "25", name: "Shivamogga" },
    { Sid: "15", Did: "26", name: "Tumakuru" },
    { Sid: "15", Did: "27", name: "Udupi" },
    { Sid: "15", Did: "28", name: "Uttara Kannada" },
    { Sid: "15", Did: "29", name: "Vijayapura" },
    { Sid: "15", Did: "30", name: "Yadgir" },
    { Sid: "16", Did: "1", name: "Alappuzha" },
    { Sid: "16", Did: "2", name: "Ernakulam" },
    { Sid: "16", Did: "3", name: "Idukki" },
    { Sid: "16", Did: "4", name: "Kannur" },
    { Sid: "16", Did: "5", name: "Kasaragod" },
    { Sid: "16", Did: "6", name: "Kollam" },
    { Sid: "16", Did: "7", name: "Kottayam" },
    { Sid: "16", Did: "8", name: "Kozhikode" },
    { Sid: "16", Did: "9", name: "Malappuram" },
    { Sid: "16", Did: "10", name: "Palakkad" },
    { Sid: "16", Did: "11", name: "Pathanamthitta" },
    { Sid: "16", Did: "12", name: "Thiruvananthapuram" },
    { Sid: "16", Did: "13", name: "Thrissur" },
    { Sid: "16", Did: "14", name: "Wayanad" },
    { Sid: "17", Did: "1", name: "Kargil" },
    { Sid: "17", Did: "2", name: "Leh Ladakh" },
    { Sid: "18", Did: "1", name: "Lakshadweep District" },
    { Sid: "19", Did: "1", name: "Agar Malwa" },
    { Sid: "19", Did: "2", name: "Alirajpur" },
    { Sid: "19", Did: "3", name: "Anuppur" },
    { Sid: "19", Did: "4", name: "Ashoknagar" },
    { Sid: "19", Did: "5", name: "Balaghat" },
    { Sid: "19", Did: "6", name: "Barwani" },
    { Sid: "19", Did: "7", name: "Betul" },
    { Sid: "19", Did: "8", name: "Bhind" },
    { Sid: "19", Did: "9", name: "Bhopal" },
    { Sid: "19", Did: "10", name: "Burhanpur" },
    { Sid: "19", Did: "11", name: "Chhatarpur" },
    { Sid: "19", Did: "12", name: "Chhindwara" },
    { Sid: "19", Did: "13", name: "Damoh" },
    { Sid: "19", Did: "14", name: "Datia" },
    { Sid: "19", Did: "15", name: "Dewas" },
    { Sid: "19", Did: "16", name: "Dhar" },
    { Sid: "19", Did: "17", name: "Dindori" },
    { Sid: "19", Did: "18", name: "East Nimar" },
    { Sid: "19", Did: "19", name: "Guna" },
    { Sid: "19", Did: "20", name: "Gwalior" },
    { Sid: "19", Did: "21", name: "Harda" },
    { Sid: "19", Did: "22", name: "Hoshangabad" },
    { Sid: "19", Did: "23", name: "Indore" },
    { Sid: "19", Did: "24", name: "Jabalpur" },
    { Sid: "19", Did: "25", name: "Jhabua" },
    { Sid: "19", Did: "26", name: "Katni" },
    { Sid: "19", Did: "27", name: "Khargone" },
    { Sid: "19", Did: "28", name: "Mandla" },
    { Sid: "19", Did: "29", name: "Mandsaur" },
    { Sid: "19", Did: "30", name: "Morena" },
    { Sid: "19", Did: "31", name: "Narsinghpur" },
    { Sid: "19", Did: "32", name: "Neemuch" },
    { Sid: "19", Did: "33", name: "Niwari" },
    { Sid: "19", Did: "34", name: "Panna" },
    { Sid: "19", Did: "35", name: "Raisen" },
    { Sid: "19", Did: "36", name: "Rajgarh" },
    { Sid: "19", Did: "37", name: "Ratlam" },
    { Sid: "19", Did: "38", name: "Rewa" },
    { Sid: "19", Did: "39", name: "Sagar" },
    { Sid: "19", Did: "40", name: "Satna" },
    { Sid: "19", Did: "41", name: "Sehore" },
    { Sid: "19", Did: "42", name: "Seoni" },
    { Sid: "19", Did: "43", name: "Shahdol" },
    { Sid: "19", Did: "44", name: "Shajapur" },
    { Sid: "19", Did: "45", name: "Sheopur" },
    { Sid: "19", Did: "46", name: "Shivpuri" },
    { Sid: "19", Did: "47", name: "Sidhi" },
    { Sid: "19", Did: "48", name: "Singrauli" },
    { Sid: "19", Did: "49", name: "Tikamgarh" },
    { Sid: "19", Did: "50", name: "Ujjain" },
    { Sid: "19", Did: "51", name: "Umaria" },
    { Sid: "19", Did: "52", name: "Vidisha" },
    { Sid: "20", Did: "1", name: "Ahmednagar" },
    { Sid: "20", Did: "2", name: "Akola" },
    { Sid: "20", Did: "3", name: "Amravati" },
    { Sid: "20", Did: "4", name: "Aurangabad" },
    { Sid: "20", Did: "5", name: "Beed" },
    { Sid: "20", Did: "6", name: "Bhandara" },
    { Sid: "20", Did: "7", name: "Buldhana" },
    { Sid: "20", Did: "8", name: "Chandrapur" },
    { Sid: "20", Did: "9", name: "Dhule" },
    { Sid: "20", Did: "10", name: "Gadchiroli" },
    { Sid: "20", Did: "11", name: "Gondia" },
    { Sid: "20", Did: "12", name: "Hingoli" },
    { Sid: "20", Did: "13", name: "Jalgaon" },
    { Sid: "20", Did: "14", name: "Jalna" },
    { Sid: "20", Did: "15", name: "Kolhapur" },
    { Sid: "20", Did: "16", name: "Latur" },
    { Sid: "20", Did: "17", name: "Mumbai" },
    { Sid: "20", Did: "18", name: "Mumbai Suburban" },
    { Sid: "20", Did: "19", name: "Nagpur" },
    { Sid: "20", Did: "20", name: "Nanded" },
    { Sid: "20", Did: "21", name: "Nandurbar" },
    { Sid: "20", Did: "22", name: "Nashik" },
    { Sid: "20", Did: "23", name: "Osmanabad" },
    { Sid: "20", Did: "24", name: "Palghar" },
    { Sid: "20", Did: "25", name: "Parbhani" },
    { Sid: "20", Did: "26", name: "Pune" },
    { Sid: "20", Did: "27", name: "Raigad" },
    { Sid: "20", Did: "28", name: "Ratnagiri" },
    { Sid: "20", Did: "29", name: "Sangli" },
    { Sid: "20", Did: "30", name: "Satara" },
    { Sid: "20", Did: "31", name: "Sindhudurg" },
    { Sid: "20", Did: "32", name: "Solapur" },
    { Sid: "20", Did: "33", name: "Thane" },
    { Sid: "20", Did: "34", name: "Wardha" },
    { Sid: "20", Did: "35", name: "Washim" },
    { Sid: "20", Did: "36", name: "Yavatmal" },
    { Sid: "21", Did: "1", name: "Bishnupur" },
    { Sid: "21", Did: "2", name: "Chandel" },
    { Sid: "21", Did: "3", name: "Churachandpur" },
    { Sid: "21", Did: "4", name: "Imphal East" },
    { Sid: "21", Did: "5", name: "Imphal West" },
    { Sid: "21", Did: "6", name: "Jiribam" },
    { Sid: "21", Did: "7", name: "Kakching" },
    { Sid: "21", Did: "8", name: "Kamjong" },
    { Sid: "21", Did: "9", name: "Kangpokpi" },
    { Sid: "21", Did: "10", name: "Noney" },
    { Sid: "21", Did: "11", name: "Pherzawl" },
    { Sid: "21", Did: "12", name: "Senapati" },
    { Sid: "21", Did: "13", name: "Tamenglong" },
    { Sid: "21", Did: "14", name: "Tengnoupal" },
    { Sid: "21", Did: "15", name: "Thoubal" },
    { Sid: "21", Did: "16", name: "Ukhrul" },
    { Sid: "22", Did: "1", name: "East Garo Hills" },
    { Sid: "22", Did: "2", name: "East Jaintia Hills" },
    { Sid: "22", Did: "3", name: "East Khasi Hills" },
    { Sid: "22", Did: "4", name: "North Garo Hills" },
    { Sid: "22", Did: "5", name: "Ri Bhoi" },
    { Sid: "22", Did: "6", name: "South Garo Hills" },
    { Sid: "22", Did: "7", name: "South West Garo Hills" },
    { Sid: "22", Did: "8", name: "South West Khasi Hills" },
    { Sid: "22", Did: "9", name: "West Garo Hills" },
    { Sid: "22", Did: "10", name: "West Jaintia Hills" },
    { Sid: "22", Did: "11", name: "West Khasi Hills" },
    { Sid: "23", Did: "1", name: "Aizawl" },
    { Sid: "23", Did: "2", name: "Champhai" },
    { Sid: "23", Did: "3", name: "Hnahthial" },
    { Sid: "23", Did: "4", name: "Khawzawl" },
    { Sid: "23", Did: "5", name: "Kolasib" },
    { Sid: "23", Did: "6", name: "Lawngtlai" },
    { Sid: "23", Did: "7", name: "Lunglei" },
    { Sid: "23", Did: "8", name: "Mamit" },
    { Sid: "23", Did: "9", name: "Saiha" },
    { Sid: "23", Did: "10", name: "Saitual" },
    { Sid: "23", Did: "11", name: "Serchhip" },
    { Sid: "24", Did: "1", name: "Dimapur" },
    { Sid: "24", Did: "2", name: "Kiphire" },
    { Sid: "24", Did: "3", name: "Kohima" },
    { Sid: "24", Did: "4", name: "Longleng" },
    { Sid: "24", Did: "5", name: "Mokokchung" },
    { Sid: "24", Did: "6", name: "Mon" },
    { Sid: "24", Did: "7", name: "Peren" },
    { Sid: "24", Did: "8", name: "Phek" },
    { Sid: "24", Did: "9", name: "Tuensang" },
    { Sid: "24", Did: "10", name: "Wokha" },
    { Sid: "24", Did: "11", name: "Zunheboto" },
    { Sid: "25", Did: "1", name: "Anugul" },
    { Sid: "25", Did: "2", name: "Balangir" },
    { Sid: "25", Did: "3", name: "Baleshwar" },
    { Sid: "25", Did: "4", name: "Bargarh" },
    { Sid: "25", Did: "5", name: "Bhadrak" },
    { Sid: "25", Did: "6", name: "Boudh" },
    { Sid: "25", Did: "7", name: "Cuttack" },
    { Sid: "25", Did: "8", name: "Deogarh" },
    { Sid: "25", Did: "9", name: "Dhenkanal" },
    { Sid: "25", Did: "10", name: "Gajapati" },
    { Sid: "25", Did: "11", name: "Ganjam" },
    { Sid: "25", Did: "12", name: "Jagatsinghapur" },
    { Sid: "25", Did: "13", name: "Jajapur" },
    { Sid: "25", Did: "14", name: "Jharsuguda" },
    { Sid: "25", Did: "15", name: "Kalahandi" },
    { Sid: "25", Did: "16", name: "Kandhamal" },
    { Sid: "25", Did: "17", name: "Kendrapara" },
    { Sid: "25", Did: "18", name: "Kendujhar" },
    { Sid: "25", Did: "19", name: "Khordha" },
    { Sid: "25", Did: "20", name: "Koraput" },
    { Sid: "25", Did: "21", name: "Malkangiri" },
    { Sid: "25", Did: "22", name: "Mayurbhanj" },
    { Sid: "25", Did: "23", name: "Nabarangpur" },
    { Sid: "25", Did: "24", name: "Nayagarh" },
    { Sid: "25", Did: "25", name: "Nuapada" },
    { Sid: "25", Did: "26", name: "Puri" },
    { Sid: "25", Did: "27", name: "Rayagada" },
    { Sid: "25", Did: "28", name: "Sambalpur" },
    { Sid: "25", Did: "29", name: "Sonepur" },
    { Sid: "25", Did: "30", name: "Sundargarh" },
    { Sid: "26", Did: "1", name: "Karaikal" },
    { Sid: "26", Did: "2", name: "Mahe" },
    { Sid: "26", Did: "3", name: "Pondicherry" },
    { Sid: "26", Did: "4", name: "Yanam" },
    { Sid: "27", Did: "1", name: "Amritsar" },
    { Sid: "27", Did: "2", name: "Barnala" },
    { Sid: "27", Did: "3", name: "Bathinda" },
    { Sid: "27", Did: "4", name: "Faridkot" },
    { Sid: "27", Did: "5", name: "Fatehgarh Sahib" },
    { Sid: "27", Did: "6", name: "Fazilka" },
    { Sid: "27", Did: "7", name: "Firozepur" },
    { Sid: "27", Did: "8", name: "Gurdaspur" },
    { Sid: "27", Did: "9", name: "Hoshiarpur" },
    { Sid: "27", Did: "10", name: "Jalandhar" },
    { Sid: "27", Did: "11", name: "Kapurthala" },
    { Sid: "27", Did: "12", name: "Ludhiana" },
    { Sid: "27", Did: "13", name: "Mansa" },
    { Sid: "27", Did: "14", name: "Moga" },
    { Sid: "27", Did: "15", name: "Pathankot" },
    { Sid: "27", Did: "16", name: "Patiala" },
    { Sid: "27", Did: "17", name: "Rupnagar" },
    { Sid: "27", Did: "18", name: "S.a.s Nagar" },
    { Sid: "27", Did: "19", name: "Sangrur" },
    { Sid: "27", Did: "20", name: "Shahid Bhagat Singh Nagar" },
    { Sid: "27", Did: "21", name: "Sri Muktsar Sahib" },
    { Sid: "27", Did: "22", name: "Tarn Taran" },
    { Sid: "28", Did: "1", name: "Ajmer" },
    { Sid: "28", Did: "2", name: "Alwar" },
    { Sid: "28", Did: "3", name: "Banswara" },
    { Sid: "28", Did: "4", name: "Baran" },
    { Sid: "28", Did: "5", name: "Barmer" },
    { Sid: "28", Did: "6", name: "Bharatpur" },
    { Sid: "28", Did: "7", name: "Bhilwara" },
    { Sid: "28", Did: "8", name: "Bikaner" },
    { Sid: "28", Did: "9", name: "Bundi" },
    { Sid: "28", Did: "10", name: "Chittorgarh" },
    { Sid: "28", Did: "11", name: "Churu" },
    { Sid: "28", Did: "12", name: "Dausa" },
    { Sid: "28", Did: "13", name: "Dholpur" },
    { Sid: "28", Did: "14", name: "Dungarpur" },
    { Sid: "28", Did: "15", name: "Ganganagar" },
    { Sid: "28", Did: "16", name: "Hanumangarh" },
    { Sid: "28", Did: "17", name: "Jaipur" },
    { Sid: "28", Did: "18", name: "Jaisalmer" },
    { Sid: "28", Did: "19", name: "Jalore" },
    { Sid: "28", Did: "20", name: "Jhalawar" },
    { Sid: "28", Did: "21", name: "Jhunjhunu" },
    { Sid: "28", Did: "22", name: "Jodhpur" },
    { Sid: "28", Did: "23", name: "Karauli" },
    { Sid: "28", Did: "24", name: "Kota" },
    { Sid: "28", Did: "25", name: "Nagaur" },
    { Sid: "28", Did: "26", name: "Pali" },
    { Sid: "28", Did: "27", name: "Pratapgarh" },
    { Sid: "28", Did: "28", name: "Rajsamand" },
    { Sid: "28", Did: "29", name: "Sawai Madhopur" },
    { Sid: "28", Did: "30", name: "Sikar" },
    { Sid: "28", Did: "31", name: "Sirohi" },
    { Sid: "28", Did: "32", name: "Tonk" },
    { Sid: "28", Did: "33", name: "Udaipur" },
    { Sid: "29", Did: "1", name: "East District" },
    { Sid: "29", Did: "2", name: "North District" },
    { Sid: "29", Did: "3", name: "South District" },
    { Sid: "29", Did: "4", name: "West District" },
    { Sid: "30", Did: "1", name: "Ariyalur" },
    { Sid: "30", Did: "2", name: "Chengalpattu" },
    { Sid: "30", Did: "3", name: "Chennai" },
    { Sid: "30", Did: "4", name: "Coimbatore" },
    { Sid: "30", Did: "5", name: "Cuddalore" },
    { Sid: "30", Did: "6", name: "Dharmapuri" },
    { Sid: "30", Did: "7", name: "Dindigul" },
    { Sid: "30", Did: "8", name: "Erode" },
    { Sid: "30", Did: "9", name: "Kallakurichi" },
    { Sid: "30", Did: "10", name: "Kanchipuram" },
    { Sid: "30", Did: "11", name: "Kanniyakumari" },
    { Sid: "30", Did: "12", name: "Karur" },
    { Sid: "30", Did: "13", name: "Krishnagiri" },
    { Sid: "30", Did: "14", name: "Madurai" },
    { Sid: "30", Did: "15", name: "Nagapattinam" },
    { Sid: "30", Did: "16", name: "Namakkal" },
    { Sid: "30", Did: "17", name: "Perambalur" },
    { Sid: "30", Did: "18", name: "Pudukkottai" },
    { Sid: "30", Did: "19", name: "Ramanathapuram" },
    { Sid: "30", Did: "20", name: "Ranipet" },
    { Sid: "30", Did: "21", name: "Salem" },
    { Sid: "30", Did: "22", name: "Sivaganga" },
    { Sid: "30", Did: "23", name: "Tenkasi" },
    { Sid: "30", Did: "24", name: "Thanjavur" },
    { Sid: "30", Did: "25", name: "The Nilgiris" },
    { Sid: "30", Did: "26", name: "Theni" },
    { Sid: "30", Did: "27", name: "Thiruvallur" },
    { Sid: "30", Did: "28", name: "Thiruvarur" },
    { Sid: "30", Did: "29", name: "Tiruchirappalli" },
    { Sid: "30", Did: "30", name: "Tirunelveli" },
    { Sid: "30", Did: "31", name: "Tirupathur" },
    { Sid: "30", Did: "32", name: "Tiruppur" },
    { Sid: "30", Did: "33", name: "Tiruvannamalai" },
    { Sid: "30", Did: "34", name: "Tuticorin" },
    { Sid: "30", Did: "35", name: "Vellore" },
    { Sid: "30", Did: "36", name: "Villupuram" },
    { Sid: "30", Did: "37", name: "Virudhunagar" },
    { Sid: "31", Did: "1", name: "Adilabad" },
    { Sid: "31", Did: "2", name: "Bhadradri Kothagudem" },
    { Sid: "31", Did: "3", name: "Hyderabad" },
    { Sid: "31", Did: "4", name: "Jagitial" },
    { Sid: "31", Did: "5", name: "Jangoan" },
    { Sid: "31", Did: "6", name: "Jayashankar Bhupalapally" },
    { Sid: "31", Did: "7", name: "Jogulamba Gadwal" },
    { Sid: "31", Did: "8", name: "Kamareddy" },
    { Sid: "31", Did: "9", name: "Karimnagar" },
    { Sid: "31", Did: "10", name: "Khammam" },
    { Sid: "31", Did: "11", name: "Kumuram Bheem Asifabad" },
    { Sid: "31", Did: "12", name: "Mahabubabad" },
    { Sid: "31", Did: "13", name: "Mahabubnagar" },
    { Sid: "31", Did: "14", name: "Mancherial" },
    { Sid: "31", Did: "15", name: "Medak" },
    { Sid: "31", Did: "16", name: "Medchal Malkajgiri" },
    { Sid: "31", Did: "17", name: "Mulugu" },
    { Sid: "31", Did: "18", name: "Nagarkurnool" },
    { Sid: "31", Did: "19", name: "Nalgonda" },
    { Sid: "31", Did: "20", name: "Narayanpet" },
    { Sid: "31", Did: "21", name: "Nirmal" },
    { Sid: "31", Did: "22", name: "Nizamabad" },
    { Sid: "31", Did: "23", name: "Peddapalli" },
    { Sid: "31", Did: "24", name: "Rajanna Sircilla" },
    { Sid: "31", Did: "25", name: "Ranga Reddy" },
    { Sid: "31", Did: "26", name: "Sangareddy" },
    { Sid: "31", Did: "27", name: "Siddipet" },
    { Sid: "31", Did: "28", name: "Suryapet" },
    { Sid: "31", Did: "29", name: "Vikarabad" },
    { Sid: "31", Did: "30", name: "Wanaparthy" },
    { Sid: "31", Did: "31", name: "Warangal Rural" },
    { Sid: "31", Did: "32", name: "Warangal Urban" },
    { Sid: "31", Did: "33", name: "Yadadri Bhuvanagiri" },
    { Sid: "32", Did: "1", name: "Dadra And Nagar Haveli" },
    { Sid: "32", Did: "2", name: "Daman" },
    { Sid: "32", Did: "3", name: "Diu" },
    { Sid: "33", Did: "1", name: "Dhalai" },
    { Sid: "33", Did: "2", name: "Gomati" },
    { Sid: "33", Did: "3", name: "Khowai" },
    { Sid: "33", Did: "4", name: "North Tripura" },
    { Sid: "33", Did: "5", name: "Sepahijala" },
    { Sid: "33", Did: "6", name: "South Tripura" },
    { Sid: "33", Did: "7", name: "Unakoti" },
    { Sid: "33", Did: "8", name: "West Tripura" },
    { Sid: "34", Did: "1", name: "Agra" },
    { Sid: "34", Did: "2", name: "Aligarh" },
    { Sid: "34", Did: "3", name: "Ambedkar Nagar" },
    { Sid: "34", Did: "4", name: "Amethi" },
    { Sid: "34", Did: "5", name: "Amroha" },
    { Sid: "34", Did: "6", name: "Auraiya" },
    { Sid: "34", Did: "7", name: "Ayodhya" },
    { Sid: "34", Did: "8", name: "Azamgarh" },
    { Sid: "34", Did: "9", name: "Baghpat" },
    { Sid: "34", Did: "10", name: "Bahraich" },
    { Sid: "34", Did: "11", name: "Ballia" },
    { Sid: "34", Did: "12", name: "Balrampur" },
    { Sid: "34", Did: "13", name: "Banda" },
    { Sid: "34", Did: "14", name: "Barabanki" },
    { Sid: "34", Did: "15", name: "Bareilly" },
    { Sid: "34", Did: "16", name: "Basti" },
    { Sid: "34", Did: "17", name: "Bhadohi" },
    { Sid: "34", Did: "18", name: "Bijnor" },
    { Sid: "34", Did: "19", name: "Budaun" },
    { Sid: "34", Did: "20", name: "Bulandshahr" },
    { Sid: "34", Did: "21", name: "Chandauli" },
    { Sid: "34", Did: "22", name: "Chitrakoot" },
    { Sid: "34", Did: "23", name: "Deoria" },
    { Sid: "34", Did: "24", name: "Etah" },
    { Sid: "34", Did: "25", name: "Etawah" },
    { Sid: "34", Did: "26", name: "Farrukhabad" },
    { Sid: "34", Did: "27", name: "Fatehpur" },
    { Sid: "34", Did: "28", name: "Firozabad" },
    { Sid: "34", Did: "29", name: "Gautam Buddha Nagar" },
    { Sid: "34", Did: "30", name: "Ghaziabad" },
    { Sid: "34", Did: "31", name: "Ghazipur" },
    { Sid: "34", Did: "32", name: "Gonda" },
    { Sid: "34", Did: "33", name: "Gorakhpur" },
    { Sid: "34", Did: "34", name: "Hamirpur" },
    { Sid: "34", Did: "35", name: "Hapur" },
    { Sid: "34", Did: "36", name: "Hardoi" },
    { Sid: "34", Did: "37", name: "Hathras" },
    { Sid: "34", Did: "38", name: "Jalaun" },
    { Sid: "34", Did: "39", name: "Jaunpur" },
    { Sid: "34", Did: "40", name: "Jhansi" },
    { Sid: "34", Did: "41", name: "Kannauj" },
    { Sid: "34", Did: "42", name: "Kanpur Dehat" },
    { Sid: "34", Did: "43", name: "Kanpur Nagar" },
    { Sid: "34", Did: "44", name: "Kasganj" },
    { Sid: "34", Did: "45", name: "Kaushambi" },
    { Sid: "34", Did: "46", name: "Kheri" },
    { Sid: "34", Did: "47", name: "Kushi Nagar" },
    { Sid: "34", Did: "48", name: "Lalitpur" },
    { Sid: "34", Did: "49", name: "Lucknow" },
    { Sid: "34", Did: "50", name: "Maharajganj" },
    { Sid: "34", Did: "51", name: "Mahoba" },
    { Sid: "34", Did: "52", name: "Mainpuri" },
    { Sid: "34", Did: "53", name: "Mathura" },
    { Sid: "34", Did: "54", name: "Mau" },
    { Sid: "34", Did: "55", name: "Meerut" },
    { Sid: "34", Did: "56", name: "Mirzapur" },
    { Sid: "34", Did: "57", name: "Moradabad" },
    { Sid: "34", Did: "58", name: "Muzaffarnagar" },
    { Sid: "34", Did: "59", name: "Pilibhit" },
    { Sid: "34", Did: "60", name: "Pratapgarh" },
    { Sid: "34", Did: "61", name: "Prayagraj" },
    { Sid: "34", Did: "62", name: "Rae Bareli" },
    { Sid: "34", Did: "63", name: "Rampur" },
    { Sid: "34", Did: "64", name: "Saharanpur" },
    { Sid: "34", Did: "65", name: "Sambhal" },
    { Sid: "34", Did: "66", name: "Sant Kabeer Nagar" },
    { Sid: "34", Did: "67", name: "Shahjahanpur" },
    { Sid: "34", Did: "68", name: "Shamli" },
    { Sid: "34", Did: "69", name: "Shravasti" },
    { Sid: "34", Did: "70", name: "Siddharth Nagar" },
    { Sid: "34", Did: "71", name: "Sitapur" },
    { Sid: "34", Did: "72", name: "Sonbhadra" },
    { Sid: "34", Did: "73", name: "Sultanpur" },
    { Sid: "34", Did: "74", name: "Unnao" },
    { Sid: "34", Did: "75", name: "Varanasi" },
    { Sid: "35", Did: "1", name: "Almora" },
    { Sid: "35", Did: "2", name: "Bageshwar" },
    { Sid: "35", Did: "3", name: "Chamoli" },
    { Sid: "35", Did: "4", name: "Champawat" },
    { Sid: "35", Did: "5", name: "Dehradun" },
    { Sid: "35", Did: "6", name: "Haridwar" },
    { Sid: "35", Did: "7", name: "Nainital" },
    { Sid: "35", Did: "8", name: "Pauri Garhwal" },
    { Sid: "35", Did: "9", name: "Pithoragarh" },
    { Sid: "35", Did: "10", name: "Rudra Prayag" },
    { Sid: "35", Did: "11", name: "Tehri Garhwal" },
    { Sid: "35", Did: "12", name: "Udam Singh Nagar" },
    { Sid: "35", Did: "13", name: "Uttar Kashi" },
    { Sid: "36", Did: "1", name: "24 Paraganas North" },
    { Sid: "36", Did: "2", name: "24 Paraganas South" },
    { Sid: "36", Did: "3", name: "Alipurduar" },
    { Sid: "36", Did: "4", name: "Bankura" },
    { Sid: "36", Did: "5", name: "Birbhum" },
    { Sid: "36", Did: "6", name: "Coochbehar" },
    { Sid: "36", Did: "7", name: "Darjeeling" },
    { Sid: "36", Did: "8", name: "Dinajpur Dakshin" },
    { Sid: "36", Did: "9", name: "Dinajpur Uttar" },
    { Sid: "36", Did: "10", name: "Hooghly" },
    { Sid: "36", Did: "11", name: "Howrah" },
    { Sid: "36", Did: "12", name: "Jalpaiguri" },
    { Sid: "36", Did: "13", name: "Jhargram" },
    { Sid: "36", Did: "14", name: "Kalimpong" },
    { Sid: "36", Did: "15", name: "Kolkata" },
    { Sid: "36", Did: "16", name: "Maldah" },
    { Sid: "36", Did: "17", name: "Medinipur East" },
    { Sid: "36", Did: "18", name: "Medinipur West" },
    { Sid: "36", Did: "19", name: "Murshidabad" },
    { Sid: "36", Did: "20", name: "Nadia" },
    { Sid: "36", Did: "21", name: "Paschim Bardhaman" },
    { Sid: "36", Did: "22", name: "Purba Bardhaman" },
    { Sid: "36", Did: "23", name: "Purulia" },
  ];