export const states = [
    { Sid: "1", name: "Andaman And Nicobar Islands" },
    { Sid: "2", name: "Andhra Pradesh" },
    { Sid: "3", name: "Arunachal Pradesh" },
    { Sid: "4", name: "Assam" },
    { Sid: "5", name: "Bihar" },
    { Sid: "6", name: "Chandigarh" },
    { Sid: "7", name: "Chhattisgarh" },
    { Sid: "8", name: "Delhi" },
    { Sid: "9", name: "Goa" },
    { Sid: "10", name: "Gujarat" },
    { Sid: "11", name: "Haryana" },
    { Sid: "12", name: "Himachal Pradesh" },
    { Sid: "13", name: "Jammu And Kashmir" },
    { Sid: "14", name: "Jharkhand" },
    { Sid: "15", name: "Karnataka" },
    { Sid: "16", name: "Kerala" },
    { Sid: "17", name: "Ladakh" },
    { Sid: "18", name: "Lakshadweep" },
    { Sid: "19", name: "Madhya Pradesh" },
    { Sid: "20", name: "Maharashtra" },
    { Sid: "21", name: "Manipur" },
    { Sid: "22", name: "Meghalaya" },
    { Sid: "23", name: "Mizoram" },
    { Sid: "24", name: "Nagaland" },
    { Sid: "25", name: "Odisha" },
    { Sid: "26", name: "Puducherry" },
    { Sid: "27", name: "Punjab" },
    { Sid: "28", name: "Rajasthan" },
    { Sid: "29", name: "Sikkim" },
    { Sid: "30", name: "Tamil Nadu" },
    { Sid: "31", name: "Telangana" },
    { Sid: "32", name: "The Dadra And Nagar Haveli And Daman And Diu" },
    { Sid: "33", name: "Tripura" },
    { Sid: "34", name: "Uttar Pradesh" },
    { Sid: "35", name: "Uttarakhand" },
    { Sid: "36", name: "West Bengal" },
  ];